### ISSUE TITLE
War Statistics

### ISSUE THREAD

**Issue by RHITNL** [alexinman/clashtracker#66]
When I try to create a overview of the clan war statistics, I get the message/error; Oh no! There's no members currently in this clan that have been in any wars.
This is strange as there are 2 wars recorded and several members have been in both wars.
This might have something to do with the database tables and field. Initial, I only ran master.sql
This was on version with commit ID 107e99c6073765197e88c5895daffabd8d995d2c.
There are a lot more SQL files in the SQL folder, should I run them as well or are they upgrade SQL files after a commit is done?

**Comment by RHITNL** [comment]
Sorry, missed the last commit apparently. This was the same issue. Closed for now

**Comment by alexinman** [comment]
@RHITNL The SQL files that have a date as a name are upgrades. Ideally, I add those upgrades to the master.sql file as well so that running master.sql will reset your database to the current version, but I missed 2 of them somehow. They were added in #63, but you should run the 2 SQL files mentioned in that PR to update your database.

The backup.sql file in the SQL folder is a backup of clashtracker.ca, which you can ignore.

**Comment by RHITNL** [comment]
Yes sorry. I was not paying attention to the last commit you made regarding the war logs/stats.
I removed all wars to be able to start over again on the latest build and with the latest SQL files inserted. Will keep you posted.

**Comment by alexinman** [comment]
Oh, you didn't need to remove all your wars. I was just about to show you this script to update your player's stats:
https://github.com/alexinman/clashtracker/blob/develop/scripts/updatePlayerWarStats.php
Sorry, it's really inefficient right now, I made it quickly one afternoon and I plan on updating it soon.

**Comment by RHITNL** [comment]
haha, you must be kidding :) Decided to start over as I tried to make the first of the 2 wars editable but I did not succeed. Almost done now :)
