### ISSUE TITLE
loot record

### ISSUE THREAD

**Issue by RHITNL** [alexinman/clashtracker#69]
I added loot for myself, 2 days in a row. When I go to player.php?playerId=1&clanId=1 it shows some average per week (all times is active) but as soon as I click past week or past month, the tracker show nothing. There is no message about to less records either.
Might have something to do with only 2 added records but that is hard to see on the interface.

**Comment by alexinman** [comment]
This is caused because your player has no defences and the javascript is blowing up. I thought I fixed that, but I guess I missed something. I'll take a look right now, might be really easy to fix.... Give me a few minutes...

**Comment by RHITNL** [comment]
Thanks!
BTW, have you seen my mail from earlier today?

**Comment by alexinman** [comment]
@RHITNL Just pushed up a commit that should fix that problem. Can you update your server and try that again? Let me know if it worked.

**Comment by RHITNL** [comment]
Tried the updated file but still no luck.

**Comment by alexinman** [comment]
Alright, let's try this. Sorry about this. 😞  
This should fix the problem. The problem was how I was counting how many defences there are to display. Your player has 1 defence but it doesn't get displayed on the player page because it's part of a war that hasn't completed yet, but I was still counting it in the Javascript by accident and then it would blow up trying to build the pie chart with no data.

**Comment by RHITNL** [comment]
Looks much better! Fix :+1:
