### ISSUE TITLE
Make code work on Ralph's server

### ISSUE THREAD

**Issue by alexinman** [alexinman/clashtracker#70]
> To make the current system run on my server, there is not a lot needed. Most of it will run out of the box only the folder structure is a little different.
> 
> The only folder that is public available via http (or https if we have a certificate) is the web folder (called www in your structure).
> 
> The other files are stored in a folder called “private” which is available via FTP. In init.php, I changed the path to
> 
> <?
> 
> require(**DIR** . '/../private/config/functions.php');
> 
> ?> so PHP and nginx can access it when needed.
> 
> Further on, I think only the email function in functions.php can be just the standard PHP one instead of the current sendgrid.
> 
> Assuming you are managing your domain yourself, you might create a sub domain like dev.clashtracker.ca and point that to my server (185.96.7.139). As soon as you have done this, I can create a “customer” account for this domain and create FTP, MySQL and all other stuff needed via my controlpanel.

**Comment by RHITNL** [comment]
I already made a simple mail function so it will work on default php mail() including headers for HTML mail. Might be useful to make a value in config.php so you can choose which mail function you'd want to use. 
Also added the default sender addresses to config.php instead of hardcoded in php for an easier config
