### ISSUE TITLE
war log

### ISSUE THREAD

**Issue by RHITNL** [alexinman/clashtracker#76]
I have an issue the system does not calculate completed wars. I was a little behind filling the wars and attacks. so once a war was finished, I filled all the values. Once ready, I created a new war (as it was already started on COC) and added players. As soon as I start a new war, the current should be closed and calculated, correct? Please see printscreen attached. 
![image](https://cloud.githubusercontent.com/assets/6173448/18181113/f4d37364-7089-11e6-94c5-bdb660ade39d.png)

**Comment by alexinman** [comment]
Are you referring to the fact that experience and damage %s aren't filled in?
Those values get filled in from Clash of Clans API. If your clan has Public War log turned off then no information for wars can be filled in from the API.

I guess we could technically calculate the experience during war completion when the API doesn't return anything....

Going to switch this to improvement since AFAIK, it's working as designed, but would be better if we calculated the experience when the API doesn't return anything.

**Comment by RHITNL** [comment]
Ah, is that so? Yes I closed the war Log in Clash because people can use the info to spy on us. Will reopen is for a couple of seconds, update and close again.
Are the values updated at War Statistics without API?

**Comment by alexinman** [comment]
Yea, the values in War Statistics are calculated based on what you input for the war players/attacks and doesn't rely on the API at all.

**Comment by RHITNL** [comment]
Yes, problem is fixed now. Sorry about this one.
Seen my latest mail btw? 

Cheers!

**Comment by alexinman** [comment]
I saw it; I've been really busy with work and other things for the past week that I haven't had any time to work on Clash Tracker or reply to your email. I'll hopefully have some spare time this weekend.

**Comment by RHITNL** [comment]
ok ok, no hurry :)
Wasn't sure because my SSL certificate ended this weekend and I forgot to update postfix

**Comment by alexinman** [comment]
Not possible anymore.. Supercell changed how clan XP worked and is not easily calculated anymore.
