### ISSUE TITLE
Adding players to war

### ISSUE THREAD

**Issue by RHITNL** [alexinman/clashtracker#77]
Last war of 30 - 30 I was late creating it and adding players.
Because of that, the war was finished and some players of the enemy war were kicked of left. Those players needed to be added manual but after 5 manual added players, the system did not allow me to ad another. The add manual option simply did not show up anymore.
In total, I needed to add 7 players and could add a max of 5.

**Comment by alexinman** [comment]
Just added a fix to develop. Can you pull down that change and try it out? The problem was legacy code from when I first started this project a year ago before Clash of Clans released their API. I would add players to the clan when you added them to the war so that you wouldn't have to add them twice. But this kind of gets in the way now since the API automatically fills your clan with who is actually in the clan. So I changed it to add and then remove and to not have the check when displaying the Add War Player page so that you can always add players that are not in the clan.

**Comment by RHITNL** [comment]
Thanks! works like a charm :+1:
